[package]
name = "rskk-core"
version = "0.1.0"
authors = ["tett23 <tett23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rskk_core"
crate-type = ["staticlib", "cdylib"]

[dependencies]
objekt = "0.1.2"
